#!/bin/sh

# This line is useful when using a Git interface like SourceTree
#	because it modify the $PATH
source ~/.bash_profile

# To not auto-correct the syntax end commit it :
# 	use 'rubocop -R ${FILES}'
#	and remove 'git add ${FILES}'

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
NC='\033[0m'

#### Check for ruby style errors ####
FILES=$(git diff --cached --name-only --diff-filter=AMC | grep "\.rb$" | cut -d " " -f2-)
printf "${green}\n[Ruby Style][Info]: Checking Ruby Style\n${NC}"
if [ -n "$FILES" ]
then
	printf "${yellow}[Ruby Style][Files]:\n"
	printf "\t%s\n" ${FILES[@]}; printf "\n${NC}"
	# Run rubocop on the staged files
	rubocop -aR ${FILES}
	
	if [ $? -ne 0 ]; then
	  printf "${red}[Ruby Style][Error]: Fix the issues and commit again\n\n${NC}"
	  exit 1
	fi
else
	printf "${green}[Ruby Style][Info]: No files to check \n${NC}"
fi

git add ${FILES}
exit 0
