#!/usr/bin/env ruby

message_file = ARGV[0]
message = File.read(message_file)

branch_name = `git symbolic-ref --short HEAD`
prefix = branch_name[/^(\w+_\d+)__/]
prefix = $1
exit 0 if prefix.nil?
prefix = prefix.gsub('_', '-')

unless /^\w+[\s_-]\d+[\s:]/.match(message) || message.start_with?('Merge')
	File.open(message_file, 'w') { |f| f.write "#{prefix} #{message}" }
end
